name: easy_bi_stepper
description: A flutter package that create easily customizable Horizontal and Vertical stepper with image.
version: 1.0.0
repository: https://github.com/Zee604/easy_bi_stepper.git

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

platforms:
  android:
  ios:
  macos:
  windows:
  linux:
